site_name: Craisy Notebook
site_url: https://note_craisy.com

theme:
  name: material
  features:
    - toc.integrate        # 把目录整合到右侧
    - navigation.sections  # 左侧更清晰（推荐）
    - navigation.expand    # 自动展开（可选）

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md

  - AI:
      - Overview: ai/index.md

  - Computer Scince:
      - Overview: cs/index.md
  
  - 论文:
    - Overview: essay/index.md
    - SNNoverall: essay/SNNoverall.md
      
  - 工具使用方法:
      - Overview: tool/index.md


